name: CI - Analysis and Tests

on:
  push:
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer and Pester
        shell: pwsh
        env:
          TEMP: ${{ runner.temp }}
          TMPDIR: ${{ runner.temp }}
        run: |
          # Install and run PSScriptAnalyzer
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -Confirm:$false
          Import-Module PSScriptAnalyzer -Force
          $findings = Invoke-ScriptAnalyzer -Path . -Recurse
          $errors = $findings | Where-Object { $_.Severity -eq 'Error' }
          if ($errors) {
            Write-Host "PSScriptAnalyzer found ERROR-level issues:" -ForegroundColor Yellow
            $errors | Format-Table -AutoSize
            exit 1
          } elseif ($findings) {
            Write-Host "PSScriptAnalyzer found non-error issues (warnings/information):" -ForegroundColor Yellow
            $findings | Where-Object { $_.Severity -ne 'Error' } | Format-Table -AutoSize
          } else {
            Write-Host "No PSScriptAnalyzer issues found." -ForegroundColor Green
          }

          # Install and run Pester (use -Path for Pester v5)
          Install-Module -Name Pester -Force -Scope CurrentUser -Confirm:$false
          Import-Module Pester -Force
          Invoke-Pester -Path 'Tests' -EnableExit
