name: CI - Analysis and Tests

on:
  push:
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer and Pester
        shell: pwsh
        run: |
          # Install and run PSScriptAnalyzer
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -Confirm:$false
          Import-Module PSScriptAnalyzer -Force
          $findings = Invoke-ScriptAnalyzer -Path . -Recurse
          if ($findings) {
            Write-Host "PSScriptAnalyzer found issues:" -ForegroundColor Yellow
            $findings | Format-Table -AutoSize
            exit 1
          } else {
            Write-Host "No PSScriptAnalyzer issues found." -ForegroundColor Green
          }

          # Install and run Pester
          Install-Module -Name Pester -Force -Scope CurrentUser -Confirm:$false
          Import-Module Pester -Force
          Invoke-Pester -Script @{ Path = 'Tests' } -EnableExit
