 uses: actions/setup-powershell@vname: CI - Pester Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v
        with:
          # Use latest supported PowerShell 7.x
          pwsh-version: 'latest'

      - name: Install Pester
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted -ErrorAction SilentlyContinue
          Install-Module -Name Pester -Scope CurrentUser -Force

      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module -Name ./CueFixer.psm1 -Force -Verbose
          Invoke-Pester -Script @{ Path = './Tests'; Output = 'Detailed' }

      - name: Run demo smoke test (dry-run)
        shell: pwsh
        run: |
          Import-Module -Name ./CueFixer.psm1 -Force -Verbose
          ./examples/run-demo.ps1
